### ISSUE TITLE
Latest release with latest code?

### ISSUE THREAD

**Issue by NancyChunlan** [wfhartford/gradle-helm#14]
Hi,
Happy new year.
We always have helm charm naming like '**-**-**'. And I see that the minus is replaced as the latest code shown, but not released yet. 
Also the 'chartDir', 'chartVersion' is cannot be configured in the latest release.
Is it possible to release the plugin with latest code?
We are looking forward to the new release of the plugin.

Thanks very much!

**Comment by wfhartford** [comment]
I've just released 1.0.0-beta-9 with the current master code.
