### ISSUE TITLE
Allow additional repos to be configured for finding chart dependencies

### ISSUE THREAD

**Issue by tanelso2** [wfhartford/gradle-helm#23]
Presently, the plugin doesn't allow for additional repositories to resolve dependencies.  This manifests as an error in our kafka's zookeeper dependency, which is NOT in the default helm repos.

Please feel free to assign this issue to me (@tanelso2) if you want me to work on a solution for it

**Comment by wfhartford** [comment]
Could you elaborate on this problem? I don't think I understand.

**Comment by tanelso2** [comment]
Sure! Sometimes we have helm charts that we are building with this plugin that have dependency charts that are from other repos besides the default ones. However, the helm installed by the plugin can't find these dependencies because it is only configured with the default repos.

The ask is basically to add some configuration ability to the plugin, so that before it does anything with the helm that it installs, it does a `helm repo add <x>` for all of the additional repos specified in the build.gradle configuration block.

Does that clear things up or are my explanations still confusing?

**Comment by bmuschko** [comment]
@wfhartford I'd be interested in this functionality as well. Are you planning to support this in the near future? What's the best way forward?

**Comment by bmuschko** [comment]
@wfhartford Could you please provide an answer to your users? Is this plugin still maintained by you? It hasn't seen a lot of changes recently.

**Comment by bmuschko** [comment]
@wfhartford Ping?! ☝️I'd definitely like to avoid forking this repository and rather contribute back.

**Comment by wfhartford** [comment]
Hi @bmuschko Sorry for the delay. I'm still happy to maintain this plugin, but don't have a lot of time to invest in it since my own use of it is very limited. If there was a pull request adding support of additional repos, I'd be happy to have a look and release a new version when that's appropriate.

**Comment by bmuschko** [comment]
@wfhartford That'd be great. I will put together a PR and send it your way. Stay tuned.

**Comment by bmuschko** [comment]
@wfhartford Provided PR https://github.com/wfhartford/gradle-helm/pull/27. Please advise.

**Comment by bmuschko** [comment]
This is done now and can be closed.
